version: 1

title: "Basic Example"

tinyrange:
  path: tinyrange

frontend:
  address: "127.0.0.1"
  port: 5100

vulnbox:
  template: vulnbox/vulnbox.yml
  init: python3 /root/init.py {{ .TeamIP }} {{ .TeamName }}
  services:
    - id: 0
      name: "hello"
      port: 5000

bots:
  enabled: true
  template: vulnbox/bot.yml
  events:
    vuln1:
      command: python3 /root/exploit1.py {{ .TeamIP }} {{ .TickSeconds }}

scorebot:
  template: scorebot/scorebot.yml
  config_file: game.json
  services:
    - id: 0
      command: python3 /root/scoring.py {{ .TeamIP }} {{ .NewFlag }}
  health_check: python3 /root/scoring.py health

scoring:
  points_per_tick: 100
  points_per_stolen_flag: 100
  points_per_lost_flag: -100

# Flags are valid for 1 second.
flag_valid_time: 1s

# The game will run for 5 seconds with 40 ticks.
tick_rate: 0.25s
duration: 5s

timeline:
  # - at: 5s
  #   event: network/open/bots
  - at: 1s
    event: bot/vuln1
  # - at: 15s
  #   event: network/open
  # - at: 25s
  #   event: scoreboard/freeze